# Generated by Django 5.1.7 on 2025-03-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('short_description', models.CharField(max_length=4000)),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=400)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('source_link', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=100, null=True)),
                ('post_published', models.DateField()),
            ],
        ),
    ]
