# Generated by Django 5.1.7 on 2025-04-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_article_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('short', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=3000)),
                ('thumbnail', models.CharField(max_length=400)),
                ('media', models.CharField(max_length=400)),
                ('summary', models.TextField(default='Default Summary')),
                ('featuredat', models.DateField()),
            ],
        ),
    ]
