# Generated by Django 5.1.7 on 2025-03-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
