# Generated by Django 5.1.7 on 2025-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
