# Generated by Django 5.1.7 on 2025-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_product_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='domain',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
