# Generated by Django 5.1.7 on 2025-03-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='domain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsapp.domain'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
